// GENERAL MODULE
export const GENERAL_SET_CONFIGS = 'GENERAL_SET_CONFIGS';
export const GENERAL_SET_FILTER = 'GENERAL_SET_FILTER';
export const GENERAL_SET_FILTER_BAR = 'GENERAL_SET_FILTER_BAR';


// CUSTOMER MODULES
export const CUSTOMER_SET_LIST = "CUSTOMER_SET_LIST";
export const CUSTOMER_SET_SELECTED = "CUSTOMER_SET_SELECTED";
export const CUSTOMER_SET_LIST_COUNT = "CUSTOMER_SET_LIST_COUNT";
export const CUSTOMER_SET_DETAIL_LOADING = "CUSTOMER_SET_DETAIL_LOADING";
export const CUSTOMER_SET_LIST_LOADING = "CUSTOMER_SET_LIST_LOADING";
export const CUSTOMER_SET_FILTER = "CUSTOMER_SET_FILTER";

// USER CARD MODULES
export const USER_SET_USER_CARDS = "USER_SET_USER_CARDS";
export const USER_SET_USER_CARDS_LIST_LOADING = "USER_SET_USER_CARDS_LIST_LOADING";
export const USER_SET_USER_CARD_DETAIL_LOADING = "USER_SET_USER_CARD_DETAIL_LOADING";


// CARD ISSUE MODULES
export const CARD_ISSUE_SET_LIST = "CARD_ISSUE_SET_LIST";
export const CARD_ISSUE_SET_LIST_COUNT = "CARD_ISSUE_SET_LIST_COUNT";
export const CARD_ISSUE_SET_LIST_LOADING = "CARD_ISSUE_SET_LIST_LOADING";
export const CARD_ISSUE_SET_EXPORT_EXCEL_LOADING = "CARD_ISSUE_SET_EXPORT_EXCEL_LOADING";
export const CARD_ISSUE_SET_FILTER = "CARD_ISSUE_SET_FILTER";


