export const FIELD_TYPE = {
    DATE: 'INPUT_DATE',
    TIME:'INPUT_TIME',
    NUMBER: 'INPUT_NUMBER',
    NUMERIC:'INPUT_NUMERIC',
    SELECT: 'INPUT_SELECT',
    SELECTSEARCH:'SELECT_SEARCH',
    TEXT: 'INPUT_TEXT',
    TEXTAREA:'INPUT_TEXTAREA',
    PASSWORD:'INPUT_PASSWORD',
    CHECKBOX:'INPUT_CHECKBOX',
    CHECKBOXGROUP:'INPUT_CHECKBOX_GROUP',
    LIST :'INPUT_LIST',
    AMOUNT:'INPUT_AMOUNT',
    HIDDEN:'INPUT_HIDDEN',
    verify:'INPUT_VERIFY',
    NUMBERANTD:'INPUT_NUMBER_ANTD',
    TAG:'INPUT_TAG',
    RADIO:'INPUT_RADIO',



};

export const FILTER_ALL_KEY = 'filter-all';